spring.datasource.url=jdbc:postgresql://localhost:5430/Cloud_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8080
