spring.application.name=tenant-management
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_platform
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

tenant.database.audit.system-user-id=84025b0a-f098-45ac-88c2-3b7b9c06258e
tenant.database.connection.username=postgres
tenant.database.connection.password=123456
tenant.database.connection.allowed-servers=localhost:5432