spring.application.name=tenant-management

spring.datasource.url=jdbc:postgresql://localhost:5432/Cloud_Platform
spring.datasource.username=postgres
spring.datasource.password=Hiremath3088

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true